# Generated by Django 5.2.3 on 2026-03-16 13:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('go', 'Go'), ('rust', 'Rust')], default='python', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', max_length=20)),
                ('share_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('stars_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('executions_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fork_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='snippets.snippet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'snippets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('language', models.CharField(default='python', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('output', models.TextField(blank=True, default='')),
                ('error_output', models.TextField(blank=True, default='')),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('memory_used_kb', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to=settings.AUTH_USER_MODEL)),
                ('snippet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='snippets.snippet')),
            ],
            options={
                'db_table': 'execution_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='snippets.snippet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stars',
            },
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['user', '-updated_at'], name='snippets_user_id_83ca30_idx'),
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['language'], name='snippets_languag_1ff740_idx'),
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['visibility', '-stars_count'], name='snippets_visibil_8824ab_idx'),
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['share_slug'], name='snippets_share_s_7604c2_idx'),
        ),
        migrations.AddIndex(
            model_name='executionhistory',
            index=models.Index(fields=['user', '-created_at'], name='execution_h_user_id_e2b120_idx'),
        ),
        migrations.AddIndex(
            model_name='executionhistory',
            index=models.Index(fields=['status'], name='execution_h_status_ecf62f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='star',
            unique_together={('user', 'snippet')},
        ),
    ]
