# Generated by Django 5.2.3 on 2026-03-16 13:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('file_extension', models.CharField(max_length=10)),
                ('docker_image', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('timeout_seconds', models.IntegerField(default=10)),
                ('memory_limit_mb', models.IntegerField(default=128)),
                ('template_code', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'supported_languages',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_executions', models.BigIntegerField(default=0)),
                ('successful_executions', models.BigIntegerField(default=0)),
                ('failed_executions', models.BigIntegerField(default=0)),
                ('average_execution_time_ms', models.FloatField(default=0)),
                ('active_users_today', models.IntegerField(default=0)),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'db_table': 'system_metrics',
                'ordering': ['-date'],
            },
        ),
    ]
